theme = "webstack"
version = "23.01.01"

# 首页网址
baseURL = "https://edui123.com"
# 标题
title = "Edui123.com"

[permalinks]
  posts = "/:filename/"

[params]
    # 副标题
    subtitle = "让教学简单一点点"
    # css和js文件的cdn
    cdn = "https://cdn.jsdelivr.net/gh/lmm214/edui@gh-pages"
    # 开启今日诗词
    jinrishici = "true"
    # 开启访问量统计
    busuanzi = "true"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true